name = "rps-game-state"
main = "dist/index.mjs"
compatibility_date = "2023-04-26"

# alarms are used to send a broadcast health check message
# useful to detect dead connections
compatibility_flags = ["durable_object_alarms"]

[build]
command = "npm install && npm run build"

[durable_objects]
bindings = [
  { name = "GAME_STATE", class_name = "GameState" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["GameState"] # Array of new classes
